[tool.poetry]
name = "proteinspy"
version = "1.0.1"
description = "A Poetry package to analyze protein structure from .cif files"
authors = ["AkhilTeja2209 <your_email@example.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://akhilteja2209.github.io/Proteinspy/"
repository = "https://github.com/AkhilTeja2209/Proteinspy"
keywords = ["protein", "bioinformatics", "cif", "pdb", "gemmi", "structure"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]

packages = [{ include = "proteinspy" }]

[tool.poetry.dependencies]
python = "^3.9"
gemmi = "*"
rich = "*"

[tool.poetry.group.dev.dependencies]
mkdocs = "^1.6"
mkdocs-material = "^9.5"

[tool.poetry.scripts]
proteinspy = "proteinspy.__main__:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"